ARG PHP_VERSION
FROM deckapp/apache_php:v${PHP_VERSION}

LABEL maintainer="Naba Kumar Das <nabad600@gmail.com>"

RUN apk update
RUN apk add php7.1-bcmath \
        php7.1-calendar \
        php7.1-mbstring \
        php7.1-exif \
        php7.1-ftp \
        php7.1-openssl \
        php7.1-zip \
        php7.1-sysvsem \
        php7.1-sysvshm \
        php7.1-sysvmsg \
        php7.1-shmop \
        php7.1-sockets \
        php7.1-zlib \
        php7.1-bz2 \
        php7.1-curl \
        php7.1-simplexml \
        php7.1-xml \
        php7.1-opcache \
        php7.1-dom \
        php7.1-xmlreader \
        php7.1-xmlwriter \
        php7.1-tokenizer \
        php7.1-ctype \
        php7.1-session \
        php7.1-fileinfo \
        php7.1-mongodb \
        php7.1-mysqli \
        php7.1-mysqlnd \
        php7.1-iconv \
        php7.1-json \
        php7.1-posix \
	php7.1-composer \
        curl \
	php7.1-pdo

COPY httpd.conf /etc/apache2/httpd.conf
ARG SERVER_ROOT

RUN sed -i "s#{SERVER_ROOT}#$SERVER_ROOT#g" /etc/apache2/httpd.conf
VOLUME [ "/var/www/" ]
WORKDIR /var/www

CMD ["/sbin/runit-wrapper"]
EXPOSE 80